frase =str('Guilda Dragões Carmesins')

print(frase[9])
print(frase[2:11])
print(frase[0::2])
print(frase[::2])
print(frase[:9])
print(len(frase))
print(frase.count('e'))
print(frase.find('video'))
print(frase.find('pokemon'))
print(frase.replace('Dragões','Pokemons'))
print('Guilda'in frase)
print(frase.lower())
print(frase.upper())
print(frase.capitalize())
print(frase.title())
print(frase.split())
print('-'.join(frase))

frase2 ='  Guilda Dragões Carmesins   '
print(frase2)
print(frase2.strip())
print(frase2.rstrip())
print(frase2.lstrip())